# deepwiki-compose.yml
services:
  deepwiki.dev:
    build:
      context: ./deepwiki-open
      dockerfile: Dockerfile.dev # or Dockerfile for production
    ports:
      - "${PORT:-8001}:${PORT:-8001}"
      - "3001:3000"
    env_file:
      - ./deepwiki-open/.env
    environment:
      - PORT=${PORT:-8001}
      - NODE_ENV=development
      - SERVER_BASE_URL=http://10.188.105.70:${PORT:-8001}
      - NEXT_PUBLIC_SERVER_BASE_URL=http://10.188.105.70:${PORT:-8001}
      - LOG_LEVEL=INFO
      - LOG_FILE_PATH=${LOG_FILE_PATH:-api/logs/application.log}
      - LLM_LOGGING_ENABLED=true
    volumes:
      - ~/.adalflow:/root/.adalflow
      - ./deepwiki-open/api/logs:/app/api/logs
      - ./local-repos:/app/local-repos
      - ./deepwiki-open/api:/app/api # For development
      - ./deepwiki-open/src:/app/src # For development
    mem_limit: 6g
    mem_reservation: 2g
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-8001}/health"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
